version: '2'
services:
  web:
    build:
      context: .
      args:
        - http_proxy=${http_proxy}
    environment:
      - REDIS_URL=redis://redis/
    ports:
      - "8000:8000"
    volumes:
      - ./projects:/app/projects
      - ./uploads:/app/uploads
    depends_on:
      - redis
  worker:
    build:
      context: .
      args:
        - http_proxy=${http_proxy}
    entrypoint: celery
    command: worker -A app.celery --loglevel=info --concurrency=1
    environment:
      - REDIS_URL=redis://redis/
    volumes:
      - ./projects:/app/projects
      - ./uploads:/app/uploads
    depends_on:
      - redis
      - web
  redis:
    image: redis
